"use server"

import { countCart } from "./countCart"
import { Cart } from "../types"
import { generateKeyCode } from "./generateKeyCode"

/**
 * Verifies the integrity and correctness of a cart.
 *
 * This function performs several checks to ensure that a cart's items and totals are consistent and have not been modified.
 *
 * 1. **Article Verification**: Checks if each item's `keyCode` matches the expected value generated by the `generateKeyCode` function.
 * 2. **Total Verification**: Compares the computed totals (e.g., total before tax, total VAT, total including tax) with the totals stored in the cart.
 * 3. **Quantity Verification**: Ensures that the total quantity of items and the number of unique items in the cart are as expected.
 *
 * If any of these checks fail and the environment is set to development, it logs the results to the console for debugging.
 *
 * @param {Cart} panier - The cart object to be verified, including items and computed totals.
 * @returns {boolean} Returns `true` if all verifications are successful; otherwise, returns `false`.
 */
export function verifCart(panier: Cart) {
	// On vérifie que les articles n'ont pas été modifiés
	const verif_articles = panier.items.every((item) => item.keyCode === generateKeyCode(item))

	// On vérifie les totaux du panier
	const calcul_panier = countCart(panier.items)

	const verif_ht = calcul_panier.total_ht === panier.total_ht
	const verif_ttc = calcul_panier.total_ttc === panier.total_ttc
	const verif_tva = calcul_panier.total_tva === panier.total_tva
	const verif_references_qty = calcul_panier.references_qty === panier.references_qty
	const verif_items_qty = calcul_panier.items_qty === panier.items_qty

	const check = verif_articles && verif_ht && verif_ttc && verif_tva && verif_references_qty && verif_items_qty

	if (!check && process.env.NODE_ENV === "development")
		console.error(verif_articles, verif_ht, verif_ttc, verif_tva, verif_references_qty, verif_items_qty)

	return check
}
